name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildAndroid:
    name: Androidbuild
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r15c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          sudo apt-get install vlc-bin
          sudo apt-get -y install libidn12
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime setup android
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.11.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib install swf 3.2.0
          haxelib git polymod-joalor64 https://github.com/Joalor64GH/polymod-joalor64
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git SScript https://github.com/TheWorldMachinima/SScript
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install hscript
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install actuate
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Configure for android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build Project.xml android --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidbuild
          path: 'export/release/android/bin/app/build/outputs/apk/debug'
